server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
spring:
  application:
    name: application
  eureka:
    client:
      serviceUrl:
        defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      preferIpAddress: true
