server:
  port: 8083
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
spring:
  application:
    name: microservice-one
  eureka:
    client:
      serviceUrl:
         defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      preferIpAddress: true


